import os

from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.exc import ArgumentError
from sqlalchemy.orm import DeclarativeBase, sessionmaker

load_dotenv(".env")

DATABASE_URL = os.getenv("DATABASE_URL")
SESSION_SECRET_KEY = os.getenv("SESSION_SECRET_KEY")


def _require_env(name: str, value: str | None) -> str:
    if value:
        cleaned_value = value.strip()
        if cleaned_value:
            return cleaned_value
    raise RuntimeError(f"Missing required environment variable: {name}")


def _clean_env_value(name: str, value: str) -> str:
    if value.startswith(f"{name}="):
        value = value.split("=", 1)[1].strip()

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1].strip()

    return value


DATABASE_URL = _require_env("DATABASE_URL", DATABASE_URL)
SESSION_SECRET_KEY = _require_env("SESSION_SECRET_KEY", SESSION_SECRET_KEY)

DATABASE_URL = _clean_env_value("DATABASE_URL", DATABASE_URL)
SESSION_SECRET_KEY = _clean_env_value("SESSION_SECRET_KEY", SESSION_SECRET_KEY)

if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

try:
    make_url(DATABASE_URL)
except ArgumentError as exc:
    raise RuntimeError(
        "Invalid DATABASE_URL. In Render, set key DATABASE_URL and put only the "
        "PostgreSQL URL as the value, for example "
        "postgresql://user:password@host:5432/database. Do not include quotes "
        "or 'DATABASE_URL=' in the value. If the password has special "
        "characters, use the connection string generated by Render."
    ) from exc

engine = create_engine(DATABASE_URL, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_database_target() -> dict[str, str]:
    url = make_url(DATABASE_URL)
    return {
        "driver": url.drivername,
        "host": url.host or "",
        "port": str(url.port or ""),
        "database": url.database or "",
        "user": url.username or "",
    }


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
