import os
from urllib.parse import quote_plus

from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.exc import ArgumentError
from sqlalchemy.orm import DeclarativeBase, sessionmaker

load_dotenv(".env")

APP_ENV = os.getenv("APP_ENV", "").strip().lower()
RAW_DATABASE_URL = os.getenv("DATABASE_URL")
MYSQL_HOST = os.getenv("MYSQL_HOST", "127.0.0.1")
MYSQL_PORT = os.getenv("MYSQL_PORT", "3306")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DB = os.getenv("MYSQL_DB")
SESSION_SECRET_KEY = os.getenv("SESSION_SECRET_KEY")


def _require_env(name: str, value: str | None) -> str:
    if value:
        cleaned_value = value.strip()
        if cleaned_value:
            return cleaned_value
    raise RuntimeError(f"Missing required environment variable: {name}")


def _clean_env_value(name: str, value: str) -> str:
    if value.startswith(f"{name}="):
        value = value.split("=", 1)[1].strip()

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1].strip()

    return value


def _is_server_environment() -> bool:
    render_env = os.getenv("RENDER", "").strip().lower() == "true"
    port_env = bool(os.getenv("PORT"))
    production_env = APP_ENV in {"prod", "production"}
    return render_env or production_env or (port_env and bool(RAW_DATABASE_URL))


def _get_database_backend() -> str:
    configured_backend = os.getenv("DATABASE_BACKEND", "").strip().lower()
    if configured_backend:
        return configured_backend
    return "postgresql" if _is_server_environment() else "mysql"


def _ensure_render_postgres_ssl_mode(database_url: str) -> str:
    url = make_url(database_url)
    host = url.host or ""
    if not url.drivername.startswith("postgresql"):
        return database_url
    if "sslmode" in url.query:
        return database_url
    if "render.com" not in host:
        return database_url

    separator = "&" if "?" in database_url else "?"
    return f"{database_url}{separator}sslmode=require"


def _build_postgres_database_url() -> str:
    database_url = _clean_env_value("DATABASE_URL", _require_env("DATABASE_URL", RAW_DATABASE_URL))
    if database_url.startswith("postgres://"):
        database_url = database_url.replace("postgres://", "postgresql://", 1)

    try:
        make_url(database_url)
    except ArgumentError as exc:
        raise RuntimeError(
            "Invalid DATABASE_URL. In Render, set key DATABASE_URL and put only the "
            "PostgreSQL URL as the value, for example "
            "postgresql://user:password@host:5432/database. Do not include quotes "
            "or 'DATABASE_URL=' in the value. If the password has special "
            "characters, use the connection string generated by Render."
        ) from exc

    return _ensure_render_postgres_ssl_mode(database_url)


def _build_mysql_database_url() -> str:
    mysql_user = _clean_env_value("MYSQL_USER", _require_env("MYSQL_USER", MYSQL_USER))
    mysql_db = _clean_env_value("MYSQL_DB", _require_env("MYSQL_DB", MYSQL_DB))
    mysql_host = _clean_env_value("MYSQL_HOST", MYSQL_HOST)
    mysql_port = _clean_env_value("MYSQL_PORT", MYSQL_PORT)
    safe_password = quote_plus(_clean_env_value("MYSQL_PASSWORD", MYSQL_PASSWORD or ""))
    return f"mysql+pymysql://{mysql_user}:{safe_password}@{mysql_host}:{mysql_port}/{mysql_db}"


DATABASE_BACKEND = _get_database_backend()
SESSION_SECRET_KEY = _clean_env_value("SESSION_SECRET_KEY", _require_env("SESSION_SECRET_KEY", SESSION_SECRET_KEY))

if DATABASE_BACKEND in {"postgres", "postgresql", "database_url"}:
    ACTIVE_DATABASE_URL = _build_postgres_database_url()
    DATABASE_SOURCE = "DATABASE_URL"
elif DATABASE_BACKEND == "mysql":
    ACTIVE_DATABASE_URL = _build_mysql_database_url()
    DATABASE_SOURCE = "MYSQL_*"
else:
    raise RuntimeError("Invalid DATABASE_BACKEND. Use 'mysql' or 'postgresql'.")

engine = create_engine(ACTIVE_DATABASE_URL, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_database_target() -> dict[str, str]:
    url = make_url(ACTIVE_DATABASE_URL)
    return {
        "backend": DATABASE_BACKEND,
        "source": DATABASE_SOURCE,
        "driver": url.drivername,
        "host": url.host or "",
        "port": str(url.port or ""),
        "database": url.database or "",
        "user": url.username or "",
    }


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
